// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Projects struct {
	ID          int64
	Owner       int32
	ProjectType int32
	Title       string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SocialUrl   []string
	SourceUrl   pgtype.Text
	Closed      pgtype.Bool
	ClosedAt    pgtype.Timestamptz
}

type Users struct {
	ID        int32
	Email     string
	UserName  string
	Password  string
	CreatedAt pgtype.Timestamptz
}
